---
all:
  hosts:
    jenkins-master-01:
      ansible_host: "{{ lookup('env','JENKINS_MASTER') | ansible.utils.ipv4 }}"
    jenkins-agent-01:
      ansible_host: "{{ lookup('env','JENKINS_AGENT') | ansible.utils.ipv4 }}"
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos